### ISSUE TITLE
keyserver issue when building docker image

### ISSUE THREAD

**Issue by justjacksonn** [appropriate/docker-jetty#14]
Not sure why, but the below bit fails for me with exit code 2. I am building using Ubunut 14.04 and Oracle JDK 8, not sure if the below doesn't execute on Ubuntu? 

ENV JETTY_GPG_KEYS 5DE533CB43DAF8BC3E372283E7AE839CD7C58886

RUN set -xe \
    && for key in $JETTY_GPG_KEYS; do \
        gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
    done

**Comment by tianon** [comment]
Are you behind a corporate firewall of some kind?

**Comment by justjacksonn** [comment]
Ok.. to add to this.. the response is below. I go to ha.pool.sks-keyservers.net, and the web page shows up, so I am able to access it. When I put in the gpg key in the ENV JETTY_GPG_KEYS step, the search fails to find it. Is the key correct.. or maybe it's old? I don't know much about this key stuff.. so groping in the dark here.

Step 16 : RUN for key in $JETTY_GPG_KEYS; do gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; done
 ---> Running in f979b68a356a
[91mgpg: directory `/root/.gnupg' created
[0m[91mgpg: new configuration file`/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
[0m[91mgpg: keyring`/root/.gnupg/secring.gpg' created
[0m[91mgpg: keyring `/root/.gnupg/pubring.gpg' created
[0m[91mgpg: requesting key D7C58886 from hkp server ha.pool.sks-keyservers.net
[0mgpgkeys: HTTP fetch error 7: couldn't connect: eof
[91mgpg: no valid OpenPGP data found.
gpg: Total number processed: 0
The command '/bin/sh -c for key in $JETTY_GPG_KEYS; do gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; done' returned a non-zero code: 2

**Comment by md5** [comment]
That "HTTP fetch error 7: couldn't connect: eof" looks suspicious. Maybe there's a bad mirror in the pool?

As far as I know, that key should be fine (cf. https://hkps.pool.sks-keyservers.net/pks/lookup?op=vindex&search=jesse.mcconnell%40gmail.com).

**Comment by sergef** [comment]
According to https://sks-keyservers.net/overview-of-pools.php they have another mirror with :80 available. To go through corporate firewall you can switch to `hkp://p80.pool.sks-keyservers.net:80` pool instead of `ha.pool.sks-keyservers.net`. Command will look like: `gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys "$key"`

**Comment by md5** [comment]
In addition to what @sergef mentioned, another way to deal with corporate firewall restrictions is to inform `apt-key`/`gpg` about your outbound HTTP proxy. This can be done by setting the `http_proxy` environment variable or by using the `--keyserver-options http-proxy=URL` command-line option.

@justjacksonn Since you're building the image from scratch with a different base OS image and a different JDK, I'd like to close this issue since it's not actually a problem with the `jetty` image distributed on Docker Hub.
