### ISSUE TITLE
Jetty not accessible from LAN in docker

### ISSUE THREAD

**Issue by abhishekamralkar** [appropriate/docker-jetty#21]
How to access Jetty running in Docker from LAN? I run jetty in ubuntu 14.04 and tried all sorts of things but no luck , my jetty server runs locally but not accessible from my machine.

**Comment by md5** [comment]
What command are you using to run your Jetty container? Are you able to access the container from the Docker host itself?

Unless you've enabled port mapping with `-p`, your container will only be accessible to other containers on the same host or from the host itself using the internal IP address of the container. That may be your problem. Otherwise, it may be a firewall issue or something else entirely.

**Comment by abhishekamralkar** [comment]
@md5  Thanks for replying. I am able to access jetty from docker itself. I am using below command

```
docker -d -p 8080:8080 abhishekamralkar/jetty 
```

and I enabled JETTY_HOST=0.0.0.0

**Comment by md5** [comment]
`JETTY_HOST` shouldn't make any difference with current versions of the image. `0.0.0.0` is the default (inside the container).

What happens when you try to access port 8080 from another host on the network? Do you see anything in `/var/log/messages` about packets being dropped?

**Comment by joakime** [comment]
This issue has been moved to the new Official Eclipse Jetty Docker repository.

See https://github.com/eclipse/jetty.docker/issues/3
