### ISSUE TITLE
Bypassing start.jar when starting Jetty

### ISSUE THREAD

**Issue by SchulteDev** [appropriate/docker-jetty#63]
Hi,

Jetty's start-time can be decreased by [bypassing start.jar](https://www.eclipse.org/jetty/documentation/9.4.x/quickstart-webapp.html#_bypassing_start_jar).

Please add this improvement to the docker-jetty images.

**Comment by gregw** [comment]
The problem with baking in the `start.jar` bypass into a base docker image, is that extended images will need to regenerate the saved commands whenever they change the jetty configuration.

It may be preferable to simply document how it can be done in a extended docker image rather than put something in the base.

I'll do that at least for a start...

**Comment by SchulteDev** [comment]
Maybe a mix? Let's say, a predefined command, which I can use in my extended docker image, or a script within the docker image for re-usage; combined with some documentation.

**Comment by md5** [comment]
@SchulteMarkus I agree with @gregw that baking this into the image is problematic. I also don't see it being much help to have a predefined command when you can pretty easily do something like this:

```Dockerfile
FROM jetty:9.4

RUN \
	echo "#!/bin/sh" > /jetty-quick-start \
	&& echo "exec $(java -jar $JETTY_HOME/start.jar --dry-run)" >> /jetty-quick-start \
	&& chmod +x /jetty-quick-start

ENTRYPOINT ["/jetty-quick-start"]
```

**Comment by SchulteDev** [comment]
I would prefer not to overwrite ENTRYPOINT from jetty-image

**Comment by gregw** [comment]
@SchulteMarkus the entry point is already a rather complex script and I'm fearful that it could be very confusing if we added quickstart support.

For example, let's say we make it auto-detect a quick-start.sh script and run it if it exists, then what should the entry point do if it passed extra argument which it would normally add to the command line passed to start.jar.

I can see somebody trying to pass args to such and image and getting very confused as to why they are not being used.

I think replacing the entrypoint is a good clear way to indicate an image is starting differently.  It's also quicker than calling a script that calls a script.

Conversely with the example posted by @md5 I can see users getting confused trying to pass in 'bash' as an argument, but having it ignored and jetty started anyway.

So perhaps the compromise is to provide a command in an image that can be run by a Dockerfile that generates a quick-start-entrypoint that does the right thing with extra args and commands, but avoids start.jar.  It could even perhaps check date stamps on the generated script vs the jetty start.d directory to warn if jetty's configuration has been changed since the script was generated.

**Comment by SchulteDev** [comment]
@gregw Thanks for you detailed statement.
I think you are right. The increased complexity, both on the docker-jetty internals as well as docker-jetty-user-site (different usecases, debugging...), do not legitimate the needed modifications. There would be disadvantages left.

A documented example would be nice, though.

I gave the [example](https://github.com/appropriate/docker-jetty/issues/63#issuecomment-301271708) written by @md5 a short try, but did not succeed. I failed when (still) using JAVA_OPTIONS, as well as my running docker-container did not handle SIGINT any more.

**Comment by md5** [comment]
Getting `$JAVA_OPTIONS` to work from `-e` would be tricky. You would either need to interpolate it into the output of `--dry-run` or the output would need to have it already.

As for `SIGINT` not working, that's a bit surprising. My example is using the `ENTRYPOINT []` form and has an `exec` in the generated script, so `java` should end up as PID 1. I just checked both the normal `jetty:9.4` container and my example and both show only a single process running. They also both respond the same way to `docker kill -s INT` by shutting down cleanly.

**Comment by gregw** [comment]
With regards to quickstarting the webapps themselves, at the moment a webapp has to self declare that it wants to be quickstarted, so it is difficult to impose quick start externally.  However, we will shortly fix that in 10.0.0, so any webapp can be made to quickstart on the second run. I may backport those changes to 9.4.0 along with a change that makes it easy to start/stop the server from a Dockerfile.  That way the server can be run briefly while building the image - which is a good check that all is OK, plus it will pre-generate any quickstart webapps.  So with the next releases, this will be much easier to achieve.   A 10.0.0.alpha is probably a few weeks away once the voting for the servlet 4.0 API is done.

**Comment by md5** [comment]
@gregw Sounds great!

**Comment by gregw** [comment]
Actually,  there are some reasons that we may want to put a start.jar bypass into the normal entrypoint.   The jetty start.jar may start jetty itself, or it may spawn another JVM to run jetty.  It does the later if there are modules enabled that have system properties or boot path configurations, as once start.jar is running it is too late to reconfigure many parts of the JVM.

So there are two issues with this: more memory is consumed as there are two JVMs;  the process doing the running is no longer PID==1 and I have seen some cloud debugging environments that assume the main process is PID==1.

So I'm thinking that the entry point instead of doing 
```
exec "$@"
```

we should do
```
CMD=$( $@ --dry-run)
exec "$CMD"
```

This will keep the main jetty process to always be PID==1 and there will only be 1 running JVM (although we would have spawned one in the dry-run).  

Once we are doing that, it probably makes sense to have a file that can short cut the dry-run (with suitable timestamp checks).

I'll do some experiments... stand by...

**Comment by gregw** [comment]
@SchulteMarkus I have merged the PR that avoids start.jar.   Please report any issues.
